=== DavidOteros/Linguaxes_de_marcas/Tema_3/XSD/DU4-Exercise25/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="photo"/>
                            <xs:element name="tags" type="xs:string" />
                            <xs:element name="diameter" type="xs:positiveInteger"/>
                            <xs:element name="weight" type="xs:positiveInteger"/>
                            <xs:element name="size" type="sizeType" minOccurs="0"/> <!--Lo hacemos asÃ­ para que no tenga aparecer siempre-->
                            <xs:element name="prize" type="priceType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Big"/>
            <xs:enumeration value="Small"/>
            <xs:enumeration value=""/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/> <!--Revisar esto-->
            <xs:fractionDigits value="2"/> <!-- Fraction Digits-->
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DavidOteros/Linguaxes_de_marcas/2ª Evaluación/Tema_3/XSD/DU4-Exercise25 - validacion simpletype/items.xml
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="items.xsd">
    <item>
        <name></name>
        <photo></photo>
        <tags></tags>
        <diameter>3</diameter>
        <weight>4</weight>
        <size>Small</size>
        <prize>12.09</prize>

    </item>
</items>


<!-- Lets assume that we have next assumptions:

    - Xml consists of zero or more items.
    - Each item has required name, photo, tags, diameter, weight, price fields and one non required enumeration size field.
    - Diameter, weight and price must be numeric, positive values.
    - Price also must be decimal with two numbers after point.
    - Size field, if present, can be one of: Big, Small, empty.-->
