<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <!-- Si ponemos standalone="yes" quiere decir que
nosotros validamos todo en el documento en cuestión sin necesitar algo a mayores para poder validar -->


<!-- INSERT DOCTYPE with subset, cando lledas a "<". Para decir que un documento é XML úsase DTD, DOCTYPE
businnes chámase igual que o nodo raíz, esto sempre é así -->
<!-- Estamos validando con un DTD, non so cumpren os datos, senon tamén a estructura-->
<!DOCTYPE business [
    <!ELEMENT business (videogame|toy|game)*> <!-- Se poñemos * significa que podemos tener de 0 videojuego a N.  Si ponemos + significa mínimo 1, máximo los que sean -->
    <!-- "|" este simbolo funciona como "OR", podemos tener videogame o toy-->
    <!ELEMENT videogame (title,developer,release_date?)> <!-- Interrogante é  Cero ou 1 -->
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT developer (#PCDATA)>
    <!ELEMENT release_date (#PCDATA)>
    <!ELEMENT toy (#PCDATA)>
    <!ATTLIST toy color NMTOKEN #IMPLIED> <!--Esto para los atributos: CDATA é o equivalente a String-->
    <!-- #REQUIRED, quere decir que é obligatorio, #IMPLIED, quere decir que pode aparecer ou non-->
    <!-- Cando poemos CDATA queremos decir que podemos poñer calcquera caracter %, € etc.-->
    <!-- Cando poñemos NMTOKEN, so podemos poñer alguns caracteres concretos, Alfabeticos, numéricos e algunha cousa mais . Recordar que esto é para os atributos-->
    <!ELEMENT game EMPTY> <!--Empty fai referencia a que está baleiro-->
]>

<business>
    <videogame>
        <title>Dragon Quest IX</title>
        <developer>Level 5</developer>
        <release_date>2009</release_date>
    </videogame>    
    <toy color="black">Story</toy>
    <videogame>
        <title>Fornite</title>
        <developer>Epic Games</developer>
    </videogame>
    <toy>Boy</toy>
    <game/>
</business>