=== DavidOteros/Linguaxes_de_marcas/2ª Evaluación/Tema_3/DTD/DU4-Exercise18/computer_shop.dtd
<!ELEMENT computer_shop (products,customers,sales)>
<!ELEMENT products (product+)>
<!ELEMENT product (title,(manufacturer|brand),model,price,stock,reconditioned?)>
<!ATTLIST product id ID #REQUIRED>
<!ATTLIST product EAN NMTOKEN #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)> <!--EMPTY QUE PUEDE NO LLEVAR NADA -->
<!ELEMENT brand (#PCDATA)> <!--EMPTY QUE PUEDE NO LLEVAR NADA -->
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency (EUR|USD) #REQUIRED>
<!ATTLIST price discount  NMTOKEN "0"> <!-- Para dar valor por defecto, se pone -->
<!ATTLIST price VAT (general|reduced|super-reduced) #REQUIRED> 
<!ELEMENT stock (#PCDATA)>
<!ELEMENT reconditioned EMPTY>
<!ELEMENT customers (customer*)>
<!ELEMENT customer (id_card,((first_name,surnames)|complete_name),telephone*, postal_address?)>
<!ATTLIST customer id ID #REQUIRED>
<!ATTLIST customer date_of_creation NMTOKEN #REQUIRED>
<!ELEMENT id_card (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT surnames (#PCDATA)>
<!ELEMENT complete_name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT postal_address (#PCDATA)>
<!ELEMENT sales (sale*)>
<!ELEMENT sale (list_of_products+,total_price,currency)>
<!ATTLIST sale date_of_sale NMTOKEN #REQUIRED>
<!ATTLIST sale customer IDREF #REQUIRED>
<!ATTLIST sale product_identifier IDREF #REQUIRED>
<!ATTLIST sale quantity_sold NMTOKEN "1">
<!ELEMENT list_of_products (#PCDATA)>
<!ELEMENT total_price (#PCDATA)>
<!ELEMENT currency (#PCDATA)>

=== DavidOteros/Linguaxes_de_marcas/Tema_3/DTD/DU4-Exercise18/computer_shop.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>


<!DOCTYPE computer_shop SYSTEM "computer_shop.dtd">
<computer_shop>
    <products>
        <product id="P1" EAN = "EAN1">
            <title>Chocolate Milka</title>
            <manufacturer>Milka</manufacturer>
            <model>Oreo</model>
            <price currency="EUR" discount="12" VAT = "general"></price>
            <stock>25</stock>
            <reconditioned></reconditioned>
        </product>
    </products>
    <customers>
        <customer id="C1" date_of_creation ="14-02-2025">
            <id_card>C1-1001</id_card>
            <first_name>David</first_name>
            <surnames>Otero</surnames>
            <telephone></telephone>
            <postal_address></postal_address>
        </customer>
    </customers>
    <sales>
        <sale date_of_sale ="" customer = "" product_identifier = "" quantity_sold = "">
            <list_of_products></list_of_products>
            <total_price></total_price>
            <currency></currency>
        </sale>
    </sales>


</computer_shop>
