<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE stock [
    <!ELEMENT stock (new-car|used-car)*>	<!--Que
    tengas que elegir entre uno y otro te permite que puedas poner en el orden que quieras-->
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>


<stock>
    <used-car>
        <model>AudiTT</model>
        <price>1000</price>
        <mileage>500000</mileage>
        <condition>good</condition>
    </used-car>
    <new-car>
        <model>Renault </model>
        <price>Capture</price>
    </new-car>
    <new-car>
        <model>Fiat</model>
        <price>2000</price>
    </new-car>
    <used-car>
        <model>Volkswagen Golf</model>
        <price>3000</price>
        <mileage>500000</mileage>
    </used-car>
</stock>