=== DavidOteros/Linguaxes_de_marcas/Examen/XSD/DU4-Exercise30/university.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="location" type="xs:string" />
                            <xs:element name="staff" type="staffType" maxOccurs="unbounded" />
                            <xs:element name="subjects" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string" />
                                                    <xs:element name="description" type="xs:string" />
                                                    <xs:element name="capacity" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="subject-id" use="required" />
                                                <xs:attribute name="staff-id" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="school-ID" type="xs:ID" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <!-- Tipo reutilizable Staff-->

    <xs:complexType name="staffType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="tittle" type="xs:string" minOccurs="0" />
            <xs:element name="category" type="categoryType" />
            <xs:element name="address" type="address" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="staff-id" type="xs:ID" use="required" />
    </xs:complexType>

    <!--Tipo Adress Grupo -->
    <xs:complexType name="address">
        <xs:sequence>
            <xs:element name="street" type="xs:string" />
            <xs:element name="suburb" type="xs:string" />
            <xs:element name="postcode" type="xs:string" />
        </xs:sequence>
    </xs:complexType>


    <!-- Restriccion staff-->
    <xs:simpleType name="categoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="academic"/>
            <xs:enumeration value="general"/>
            <xs:enumeration value="technical"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== DavidOteros/Linguaxes_de_marcas/Examen/XSD/DU4-Exercise30/university.xml
<university xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="university.xsd">

    <school school-ID="SC-01">
        <name>Vales Villamarin</name>
        <location>Betanzos</location>
        
        <staff staff-id="ST-01">
            <name>Manuel</name>
            <tittle>Ingeniero</tittle> <!-- Pode non aparecer-->
            <category>general</category>
            <address> <!-- PODE TER VARIOS ADRESS-->
                <street>Rueiro de Figueiriñas</street>
                <suburb>Santiago</suburb>
                <postcode>15702</postcode>
            </address>
        </staff>

        <staff staff-id="ST-02">
            <name>Pablo</name>
            <tittle>Biologo</tittle> <!-- Pode non aparecer-->
            <category>academic</category>
            <address> <!-- PODE TER VARIOS ADRESS-->
                <street>As Mariñas</street>
                <suburb>Santiago</suburb>
                <postcode>15705</postcode>
            </address>
        </staff>

        <subjects>
            <subject subject-id="SU-01" staff-id="ST-01 ST-02"> <!-- Ensinada polo menos 1 -->
                <name>Biologia</name>
                <description>Cosas de biologia</description>
                <capacity>200</capacity> <!-- Capacidade menor 6 non é valido, maxima 400-->
            </subject>
        </subjects>


        <subjects>
            <subject subject-id="SU-02" staff-id="ST-02"> <!-- Ensinada polo menos 1 -->
                <name>Quimica</name>
                <description>Cosas de quimica</description>
                <capacity>6</capacity> <!-- Capacidade menor 6 non é valido, maxima 400-->
            </subject>
        </subjects>

    </school>





</university>
