<?xml version="1.0" encoding="UTF-8" ?>



<!DOCTYPE shiporder [
    <!ELEMENT shiporder (orderperson,shipto,item+)>
    <!ATTLIST shiporder orderid CDATA #REQUIRED>
    <!ELEMENT orderperson (#PCDATA)>
    <!ELEMENT shipto (name, address, city, country)> <!-- QUE VAYA ENTRE PARENTESIS YA QUIERE DECIR QUE ES OBLIGATORIO DE POR SI -->
    <!ELEMENT name (#PCDATA) >
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT item (title,note?,quantity,price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT note (#PCDATA)>
    <!ELEMENT quantity (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>

<shiporder orderid="889923">
    <orderperson>María Casares</orderperson>
    <shipto>
        <name>Carlos Quintana</name>
        <address>Rúa do home santo,5-1º</address>
        <city>Santiago de Compostela</city>
        <country>España</country>
    </shipto>
    <item>
        <title>Stolen</title>
        <note>Special Edition</note>
        <quantity>1</quantity>
        <price>15.90</price>
    </item>
    <item>
        <title>Ulysses</title>
        <quantity>1</quantity>
        <price>29.90</price>
    </item>
</shiporder>	