=== DavidOteros/Linguaxes_de_marcas/Examen/XSD/GROUPS/purchaseorder.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:complexType name="PurchaseOrderType">
        <xsd:sequence>
            <xsd:group ref="toGroup"/>
            <xsd:element minOccurs="0" ref="comment" />
            <xsd:element name="items" type="Items" />
        </xsd:sequence>
        <xsd:attribute name="orderDate" type="xsd:date" />
    </xsd:complexType>
    <xsd:complexType name="USAddress">
        <xsd:group ref="USDAdressGroup"/>
        <xsd:attribute fixed="US" name="country" type="xsd:NMTOKEN" />
    </xsd:complexType>
    <xsd:complexType name="Items">
        <xsd:choice >  <!-- Creacion de un choice, para elexir entre item y service dentro do propio ITEMS -->  <!--Probar con all-->
            <xsd:element name="service" minOccurs="0" type="xsd:string"></xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="item">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="productName" type="xsd:string" />
                        <xsd:element name="quantity">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:positiveInteger">
                                    <xsd:maxExclusive value="100" />
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="USPrice" type="xsd:decimal" />
                        <xsd:element minOccurs="0" ref="comment" />
                        <xsd:element minOccurs="0" name="shipDate" type="xsd:date" />
                    </xsd:sequence>
                    <xsd:attributeGroup ref="itemAtrrGroup"></xsd:attributeGroup> <!-- Creamos la referencia al grupo de atributos, estos no tienen ni que llevar sequence ni nada-->
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
    </xsd:complexType>
    <xsd:simpleType name="SKU">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{3}-[A-Z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="purchaseOrder" type="PurchaseOrderType" />
    <xsd:element name="comment" type="xsd:string" />
    <xsd:group name="USDAdressGroup">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="street" type="xsd:string" />
            <xsd:element name="city" type="xsd:string" />
            <xsd:element name="state" type="xsd:string" />
            <xsd:element name="zip" type="xsd:decimal" />
        </xsd:sequence>
    </xsd:group>
    <xsd:group name="toGroup">
        <xsd:sequence>
            <xsd:element name="shipTo" type="USAddress" />
            <xsd:element name="billTo" type="USAddress" />
        </xsd:sequence>
    </xsd:group>
    <!-- Vamos a crear un grupo de atributos-->
    <xsd:attributeGroup name="itemAtrrGroup">
        <xsd:attribute name="partNum" type="SKU" use="required" />
        <xsd:attribute name="isOutDate" type="xsd:boolean" /> <!-- Os atributos sempre van dentro dos complex type no final, sino llevan use es optional-->
    </xsd:attributeGroup>

</xsd:schema>

=== DavidOteros/Linguaxes_de_marcas/Examen/XSD/DU4-Exercise21/purchaseOrder.xml
<?xml version="1.0" encoding="UTF-8"?>

<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="purchaseOrder.xsd" orderDate="2000-01-01"> 

    <shipTo country="US">
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip>14.300</zip>
    </shipTo>

    <billTo country="US">
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip>15.300</zip>
    </billTo>

    <comment>Holaaa</comment>

    <items>
        <item partNum="123-AV">
            <productName></productName>
            <quantity>33</quantity>
            <USPrice>23</USPrice>
            <comment></comment>
            <shipDate>2014-02-12</shipDate>
        </item>
    </items>



</purchaseOrder>

=== DavidOteros/Linguaxes_de_marcas/Tema_3/XSD/DU4-Exercise21/purchaseOrder.xml
<?xml version="1.0" encoding="UTF-8"?>

<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="purchaseOrder.xsd" orderDate="2025-02-13">
    <shipTo country="US">
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip>200.12</zip>
    </shipTo>
    <billTo country="US">
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip>200.12</zip>
    </billTo>
    <comment></comment>
    <items>
        <item partNum="123-AB">
            <productName></productName>
            <quantity>1</quantity>
            <USPrice>20</USPrice>
            <shipDate>2025-02-13</shipDate>
        </item>
    </items>
</purchaseOrder>

=== DavidOteros/Linguaxes_de_marcas/Examen/XSD/GROUPS/purchaseorder.xml
<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="purchaseorder.xsd">
    <shipTo>
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip>12.300</zip>
    </shipTo>
    <billTo>
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip>13.223</zip>
    </billTo>
    <comment></comment>
    <items>
        <!-- <item partNum="235-HD" isOutDate="false">
            <productName></productName>
            <quantity>1</quantity>
            <USPrice>20</USPrice>
            <comment>Important</comment>
            <shipDate>2000-01-01</shipDate>
        </item> -->
        <service>
        Web pages development
        </service>
    </items>

</purchaseOrder>

<!-- Enumerados para atributos y choice para los elmentos REVISAR!!!-->
